const express=require('express');const crypto=require('crypto');const path=require('path');const Database=require('better-sqlite3');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');
const app=express();const PORT=process.env.PORT||3000;const SECRET=process.env.JWT_SECRET||'change-this-secret-in-production';const db=new Database('scriptvault.db');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,created_at INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS scripts(id TEXT PRIMARY KEY,user_id INTEGER NOT NULL,name TEXT NOT NULL,code TEXT NOT NULL,password_hash TEXT,enabled INTEGER NOT NULL DEFAULT 1,loads INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id));`);
app.use(express.json({limit:'3mb'}));app.use(express.static(path.join(__dirname,'public')));
const hash=s=>crypto.createHash('sha256').update(s,'utf8').digest('hex');const makeId=()=>crypto.randomBytes(9).toString('base64url');
function tokenFor(u){return jwt.sign({id:u.id,username:u.username},SECRET,{expiresIn:'7d'})}function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))throw 0;req.user=jwt.verify(h.slice(7),SECRET);next()}catch(e){res.status(401).json({error:'Non authentifié.'})}}
app.post('/api/register',async(req,res)=>{const username=String(req.body?.username||'').trim();const password=String(req.body?.password||'');if(!/^[A-Za-z0-9_]{3,24}$/.test(username))return res.status(400).json({error:'Pseudo: 3-24 caractères, lettres/chiffres/_.'.replace('_.','_ et chiffres.')});if(password.length<6)return res.status(400).json({error:'Mot de passe: 6 caractères minimum.'});try{const r=db.prepare('INSERT INTO users(username,password_hash,created_at) VALUES(?,?,?)').run(username,await bcrypt.hash(password,12),Date.now());const u={id:r.lastInsertRowid,username};res.json({token:tokenFor(u),user:u})}catch(e){res.status(409).json({error:'Ce pseudo existe déjà.'})}});
app.post('/api/login',async(req,res)=>{const username=String(req.body?.username||'').trim();const password=String(req.body?.password||'');const u=db.prepare('SELECT * FROM users WHERE username=?').get(username);if(!u||!(await bcrypt.compare(password,u.password_hash)))return res.status(401).json({error:'Identifiants incorrects.'});res.json({token:tokenFor(u),user:{id:u.id,username:u.username}})});
app.get('/api/me',auth,(req,res)=>res.json({user:req.user}));
app.get('/api/scripts',auth,(req,res)=>res.json({scripts:db.prepare('SELECT id,name,enabled,loads,created_at,updated_at FROM scripts WHERE user_id=? ORDER BY created_at DESC').all(req.user.id)}));
app.post('/api/scripts',auth,(req,res)=>{const name=String(req.body?.name||'').trim().slice(0,80);const code=String(req.body?.code||'');const pw=String(req.body?.password||'');if(!name||!code.trim())return res.status(400).json({error:'Nom et code requis.'});if(code.length>1500000)return res.status(413).json({error:'Script trop volumineux.'});let id;do{id=makeId()}while(db.prepare('SELECT id FROM scripts WHERE id=?').get(id));db.prepare('INSERT INTO scripts(id,user_id,name,code,password_hash,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(id,req.user.id,name,code,pw?hash(pw):null,Date.now(),Date.now());res.json({id,name,loader:`loadstring(game:HttpGet("${req.protocol}://${req.get('host')}/raw/${id}"))()`})});
app.put('/api/scripts/:id',auth,(req,res)=>{const s=db.prepare('SELECT * FROM scripts WHERE id=? AND user_id=?').get(req.params.id,req.user.id);if(!s)return res.status(404).json({error:'Script introuvable.'});const name=String(req.body?.name??s.name).trim().slice(0,80);const code=String(req.body?.code??s.code);const pw=String(req.body?.password||'');db.prepare('UPDATE scripts SET name=?,code=?,password_hash=?,updated_at=? WHERE id=?').run(name,code,pw?hash(pw):s.password_hash,Date.now(),s.id);res.json({ok:true})});
app.delete('/api/scripts/:id',auth,(req,res)=>{const r=db.prepare('DELETE FROM scripts WHERE id=? AND user_id=?').run(req.params.id,req.user.id);if(!r.changes)return res.status(404).json({error:'Script introuvable.'});res.json({ok:true})});
app.post('/api/scripts/:id/toggle',auth,(req,res)=>{const s=db.prepare('SELECT * FROM scripts WHERE id=? AND user_id=?').get(req.params.id,req.user.id);if(!s)return res.status(404).json({error:'Script introuvable.'});db.prepare('UPDATE scripts SET enabled=? WHERE id=?').run(s.enabled?0:1,s.id);res.json({enabled:!s.enabled})});
app.get('/raw/:id',async(req,res)=>{const s=db.prepare('SELECT * FROM scripts WHERE id=?').get(req.params.id);if(!s||!s.enabled)return res.status(404).type('text/plain').send('-- Script unavailable');if(s.password_hash){const supplied=String(req.query.key||'');if(!supplied||hash(supplied)!==s.password_hash)return res.status(403).type('text/plain').send('-- Protected script: provide ?key=...');}db.prepare('UPDATE scripts SET loads=loads+1 WHERE id=?').run(s.id);res.type('text/plain; charset=utf-8').send(s.code)});
app.get('/view/:id',(req,res)=>res.sendFile(path.join(__dirname,'public','view.html')));app.use((req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));app.listen(PORT,()=>console.log(`ScriptVault Roblox: http://localhost:${PORT}`));
